// packages/fiber/src/solid/web/Canvas.tsx
/** @jsxImportSource solid-js */
import * as THREE from 'three'
import { extend, createRoot, unmountComponentAtNode, RenderProps } from '../index'
import { createPointerEvents } from '../../web/events'
import { DomEvent } from '../../core/events'
import { createComputed, Ref, JSX, ComponentProps, mergeProps } from 'solid-js'
import { createEffect, splitProps } from 'solid-js'

export interface Props extends Omit<RenderProps<HTMLCanvasElement>, 'size'>, ComponentProps<'div'> {
  children: JSX.Element
  /** Canvas fallback content, similar to img's alt prop */
  fallback?: JSX.Element
  /**
   * Options to pass to useMeasure.
   * @see https://github.com/pmndrs/react-use-measure#api
   */
  // resize?: ResizeOptions
  /** The target where events are being subscribed to, default: the div that wraps canvas */
  eventSource?: HTMLElement
  /** The event prefix that is cast into canvas pointer x/y events, default: "offset" */
  eventPrefix?: 'offset' | 'client' | 'page' | 'layer' | 'screen'
}

/**
 * A DOM canvas which accepts threejs elements as children.
 * @see https://docs.pmnd.rs/react-three-fiber/api/canvas
 */
export function Canvas(props: Props) {
  // Create a known catalogue of Threejs-native elements
  // This will include the entire THREE namespace by default, users can extend
  // their own elements by using the createRoot API instead
  createComputed(() => extend(THREE), [])

  const [other, threeProps] = splitProps(
    mergeProps(
      {
        events: createPointerEvents,
      },
      props,
    ),
    ['children'],
  )

  // const [containerRef, containerRect] = useMeasure({ scroll: true, debounce: { scroll: 50, resize: 0 }, ...resize })
  let containerRef: HTMLDivElement = null!,
    canvasRef: HTMLCanvasElement = null!,
    divRef: HTMLDivElement = null!

  createEffect(() => {
    let size = canvasRef.parentElement?.getBoundingClientRect() ?? {
      width: 0,
      height: 0,
      top: 0,
      left: 0,
    }

    let root = createRoot<HTMLElement>(canvasRef)

    root.configure({
      ...threeProps,
      size,
      // Pass mutable reference to onPointerMissed so it's free to update
      onPointerMissed: (...args) => props.onPointerMissed?.(...args),
      onCreated: (state) => {
        // Connect to event source
        console.log('heree', state.events.connect)
        state.events.connect?.(props.eventSource ? props.eventSource : divRef)
        // Set up compute function
        if (props.eventPrefix) {
          state.setEvents({
            compute: (event, state) => {
              const x = event[(props.eventPrefix + 'X') as keyof DomEvent] as number
              const y = event[(props.eventPrefix + 'Y') as keyof DomEvent] as number
              state.pointer.set((x / state.size.width) * 2 - 1, -(y / state.size.height) * 2 + 1)
              state.raycaster.setFromCamera(state.pointer, state.camera)
            },
          })
        }
        // Call onCreated callback
        props.onCreated?.(state)
      },
    })

    root.render(props)
  })

  return (
    <div ref={divRef} style={{ position: 'relative', width: '100%', height: '100%', overflow: 'hidden' }}>
      <div ref={containerRef} style={{ width: '100%', height: '100%' }}>
        <canvas ref={canvasRef} style={{ display: 'block' }} />
      </div>
    </div>
  )
}

// packages/fiber/src/web/Canvas.tsx
import * as React from 'react'
import * as THREE from 'three'
import useMeasure from 'react-use-measure'
import type { Options as ResizeOptions } from 'react-use-measure'
import { SetBlock, Block, ErrorBoundary } from '../react/utils'
import { useMutableCallback, useIsomorphicLayoutEffect } from '../react/hooks'
import { ReconcilerRoot, extend, createRoot, unmountComponentAtNode, RenderProps } from '../react'
import { createPointerEvents } from './events'
import { DomEvent } from '../core/events'

export interface CanvasProps
  extends Omit<RenderProps<HTMLCanvasElement>, 'size'>,
    React.HTMLAttributes<HTMLDivElement> {
  children: React.ReactNode
  /** Canvas fallback content, similar to img's alt prop */
  fallback?: React.ReactNode
  /**
   * Options to pass to useMeasure.
   * @see https://github.com/pmndrs/react-use-measure#api
   */
  resize?: ResizeOptions
  /** The target where events are being subscribed to, default: the div that wraps canvas */
  eventSource?: HTMLElement
  /** The event prefix that is cast into canvas pointer x/y events, default: "offset" */
  eventPrefix?: 'offset' | 'client' | 'page' | 'layer' | 'screen'
}

/**
 * A DOM canvas which accepts threejs elements as children.
 * @see https://docs.pmnd.rs/react-three-fiber/api/canvas
 */
export const Canvas = /*#__PURE__*/ React.forwardRef<HTMLCanvasElement, CanvasProps>(function Canvas(
  {
    children,
    fallback,
    resize,
    style,
    gl,
    events = createPointerEvents,
    eventSource,
    eventPrefix,
    shadows,
    linear,
    flat,
    legacy,
    orthographic,
    frameloop,
    dpr,
    performance,
    raycaster,
    camera,
    onPointerMissed,
    onCreated,
    stages,
    ...props
  },
  forwardedRef,
) {
  // Create a known catalogue of Threejs-native elements
  // This will include the entire THREE namespace by default, users can extend
  // their own elements by using the createRoot API instead
  React.useMemo(() => extend(THREE), [])

  const [containerRef, containerRect] = useMeasure({ scroll: true, debounce: { scroll: 50, resize: 0 }, ...resize })
  const canvasRef = React.useRef<HTMLCanvasElement>(null!)
  const divRef = React.useRef<HTMLDivElement>(null!)
  const [canvas, setCanvas] = React.useState<HTMLCanvasElement | null>(null)
  React.useImperativeHandle(forwardedRef, () => canvasRef.current)

  const handlePointerMissed = useMutableCallback(onPointerMissed)
  const [block, setBlock] = React.useState<SetBlock>(false)
  const [error, setError] = React.useState<any>(false)

  // Suspend this component if block is a promise (2nd run)
  if (block) throw block
  // Throw exception outwards if anything within canvas throws
  if (error) throw error

  const root = React.useRef<ReconcilerRoot<HTMLElement>>(null!)

  if (containerRect.width > 0 && containerRect.height > 0 && canvas) {
    if (!root.current) root.current = createRoot<HTMLElement>(canvas)
    root.current.configure({
      gl,
      events,
      shadows,
      linear,
      flat,
      legacy,
      orthographic,
      frameloop,
      dpr,
      performance,
      raycaster,
      camera,
      stages,
      size: containerRect,
      // Pass mutable reference to onPointerMissed so it's free to update
      onPointerMissed: (...args) => handlePointerMissed.current?.(...args),
      onCreated: (state) => {
        // Connect to event source
        state.events.connect?.(eventSource ? eventSource : divRef.current)
        // Set up compute function
        if (eventPrefix) {
          state.setEvents({
            compute: (event, state) => {
              const x = event[(eventPrefix + 'X') as keyof DomEvent] as number
              const y = event[(eventPrefix + 'Y') as keyof DomEvent] as number
              state.pointer.set((x / state.size.width) * 2 - 1, -(y / state.size.height) * 2 + 1)
              state.raycaster.setFromCamera(state.pointer, state.camera)
            },
          })
        }
        // Call onCreated callback
        onCreated?.(state)
      },
    })
    root.current.render(
      <ErrorBoundary set={setError}>
        <React.Suspense fallback={<Block set={setBlock} />}>{children}</React.Suspense>
      </ErrorBoundary>,
    )
  }

  useIsomorphicLayoutEffect(() => {
    setCanvas(canvasRef.current)
  }, [])

  React.useEffect(() => {
    if (canvas) return () => unmountComponentAtNode(canvas!)
  }, [canvas])

  return (
    <div
      ref={divRef}
      style={{ position: 'relative', width: '100%', height: '100%', overflow: 'hidden', ...style }}
      {...props}>
      <div ref={containerRef} style={{ width: '100%', height: '100%' }}>
        <canvas ref={canvasRef} style={{ display: 'block' }}>
          {fallback}
        </canvas>
      </div>
    </div>
  )
})
